export const searchDatas = [
    {
        name: "직무",
        boxType: "checkbox",
        class: "jobs",
        types: [
            "서버/백엔드",
            "게임서버",
            "프론트엔드",
            "시스템/네트워크",
            "웹 풀스택",
            "시스템/소프트웨어",
            "안드로이드 앱",
            "데브옵스",
            "아이폰 앱",
            "인터넷 보안",
            "머신러닝",
            "임베디드 소프트웨어",
            "인공지능(AI)",
            "로보틱스 미들웨어",
            "데이터 엔지니어",
            "QA",
            "DBA",
            "사물인터넷(IoT)",
            "모바일 게임",
            "응용 프로그램",
            "게임 클라이언트",
            "블록체인",
        ],
    },
    {
        name: "경력",
        boxType: "radio",
        class: "career",
        types: [
            "전체",
            "신입",
            "1년 경력",
            "2년 경력",
            "3년 경력",
            "4년 경력",
            "5년 경력",
            "6년 경력",
            "7년 경력",
            "8년 경력",
            "9년 경력",
        ],
    },
    {
        name: "연봉",
        boxType: "radio",
        class: "wage",
        types: [
            "3,000 이상",
            "3,500 이상",
            "4,000 이상",
            "4,500 이상",
            "5,000 이상",
            "5,500이상",
            "6,000 이상",
            "6,500이상",
            "7,000 이상",
            "7,500이상",
            "8,000 이상",
        ],
    },
    {
        name: "직원 수",
        boxType: "radio",
        class: "people",
        types: ["전체", "5명 이상", "20명 이상", "100명 이상"],
    },
    {
        name: "지역",
        boxType: "radio",
        class: "place",
        types: [
            "도심/북부권",
            "동부권",
            "서북권",
            "강남권",
            "서남권",
            "판교/분당권",
            "기타 수도권",
            "수도권 외",
        ],
    },
    {
        name: "포지션 테마",
        boxType: "radio",
        class: "positionTheme",
        types: [
            "신입 연봉 4천 이상",
            "병역 특례",
            "시리즈 투자",
            "리모트 근무",
            "주 40시간 미만 근무",
        ],
    },
];
export const searchInputData = [
    {
        placeholder: "기술 스택 검색",
        class: "tech",
    },
    {
        placeholder: "회사 이름 검색",
        name: "company",
    },
];
